src/config/routes.rb
Rails.application.routes.draw do
  resources :homes
  root 'homes#index'
  resources :tracks
  resources :employees
  resources :crews
  resources :locomotives
  resources :wagons
  resources :ways
  resources :passengers
  resources :stops
  resources :stations
  get '/report_wagon' , to: 'wagons#report'
  get '/report_way' , to: 'ways#report'
  get '/report_1' , to: 'homes#track_delay'
  get '/report_2' , to: 'homes#report2'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

src/app/models/crew.rb
class Crew < ApplicationRecord
  has_many :employee_crews, dependent: :destroy
end

src/app/models/employee.rb
class Employee < ApplicationRecord
  has_many :work_histories, dependent: :destroy
  has_many :employee_crews, dependent: :destroy
end

src/app/models/employee_crew.rb
class EmployeeCrew < ApplicationRecord
  belongs_to :crew
  belongs_to :employee
end

src/app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :passenger
  belongs_to :way
end

src/app/models/home.rb
class Home < ApplicationRecord
end

src/app/models/locomotive.rb
class Locomotive < ApplicationRecord
  has_many :ways, dependent: :destroy
end

src/app/models/passenger.rb
class Passenger < ApplicationRecord

  has_many :feedbacks, dependent: :destroy
end

src/app/models/station.rb
class Station < ApplicationRecord
  has_many :stops, dependent: :destroy
end

src/app/models/stop.rb
class Stop < ApplicationRecord
  belongs_to :track
  belongs_to :station
end

src/app/models/track.rb
class Track < ApplicationRecord
  has_many :ways, dependent: :destroy
  has_many :stops, dependent: :destroy
end

src/app/models/wagon.rb
class Wagon < ApplicationRecord
  has_many :wagon_usage, dependent: :destroy
end

src/app/models/wagon_usage.rb
class WagonUsage < ApplicationRecord
  belongs_to :wagon
  belongs_to :way
end

src/app/models/way.rb
class Way < ApplicationRecord
  belongs_to :track
  belongs_to :locomotive
  has_many :feedbacks, dependent: :destroy
  has_many :work_histories, dependent: :destroy
  has_many :wagon_usage, dependent: :destroy
end

src/app/models/work_history.rb
class WorkHistory < ApplicationRecord
  belongs_to :way
  belongs_to :employee
end

src/app/controllers/stops_controller.rb
class StopsController < ApplicationController
  before_action :set_stop, only: [:show, :edit, :update, :destroy]

  # GET /stops
  # GET /stops.json
  def index
    @stops = Stop.all.paginate(:page => params[:page], :per_page => 50)
  end

  # GET /stops/1
  # GET /stops/1.json
  def show
  end

  # GET /stops/new
  def new
    @stop = Stop.new
  end

  # GET /stops/1/edit
  def edit
  end

  # POST /stops
  # POST /stops.json
  def create
    Stop.transaction do
    @stop = Stop.new(stop_params)

    respond_to do |format|
      if @stop.save
        format.html { redirect_to @stop, notice: 'Stop was successfully created.' }
        format.json { render :show, status: :created, location: @stop }
      else
        format.html { render :new }
        format.json { render json: @stop.errors, status: :unprocessable_entity }
      end
      end
    end
  end

  # PATCH/PUT /stops/1
  # PATCH/PUT /stops/1.json
  def update
    Stop.transaction do
    respond_to do |format|
      if @stop.update(stop_params)
        format.html { redirect_to @stop, notice: 'Stop was successfully updated.' }
        format.json { render :show, status: :ok, location: @stop }
      else
        format.html { render :edit }
        format.json { render json: @stop.errors, status: :unprocessable_entity }
      end
      end
    end
  end

  # DELETE /stops/1
  # DELETE /stops/1.json
  def destroy
    Stop.transaction do
    @stop.destroy
    respond_to do |format|
      format.html { redirect_to stops_url, notice: 'Stop was successfully destroyed.' }
      format.json { head :no_content }
    end
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stop
      @stop = Stop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stop_params
      params.require(:stop).permit(:order, :station_id, :track_id)
    end
end

src/app/helpers/crews_helper.rb
module CrewsHelper
end

src/app/helpers/employees_helper.rb
module EmployeesHelper
end

src/app/helpers/homes_helper.rb
module HomesHelper
end

src/app/helpers/stations_helper.rb
module StationsHelper
end

src/app/helpers/stops_helper.rb
module StopsHelper
end

src/app/helpers/tracks_helper.rb
module TracksHelper
end

src/app/helpers/wagons_helper.rb
module WagonsHelper
end

src/app/helpers/ways_helper.rb
module WaysHelper
end

src/app/views/stops/_form.html.erb
<%= form_with(model: stop, local: true) do |form| %>
  <% if stop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stop.errors.count, "error") %> prohibited this stop from being saved:</h2>

      <ul>
      <% stop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :order %>
    <%= form.number_field :order, id: :stop_order %>
  </div>

  <div class="field">
    <%= form.label :track_id %>
    <%= form.number_field :track_id, id: :stop_order %>
  </div>

  <div class="field">
    <%= form.label :station_id %>
    <%= form.number_field :station_id, id: :stop_order %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

src/app/views/stops/edit.html.erb
<h1>Editing Stop</h1>

<%= render 'form', stop: @stop %>

<%= link_to 'Show', @stop %> |
<%= link_to 'Back', stops_path %>

src/app/views/stops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stops</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stops.each do |stop| %>
      <tr>
        <td><%= stop.order %></td>
        <td><%= link_to 'Show', stop %></td>
        <td><%= link_to 'Edit', edit_stop_path(stop) %></td>
        <td><%= link_to 'Destroy', stop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= will_paginate @stops %>
<%= link_to 'New Stop', new_stop_path %>

src/app/views/stops/new.html.erb
<h1>New Stop</h1>

<%= render 'form', stop: @stop %>

<%= link_to 'Back', stops_path %>

src/app/views/stops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @stop.order %>
</p>

<p>
  <strong>Station:</strong>
  <%= @stop.station.label %>
</p>
<p>
  <strong>Track number:</strong>
  <%= @stop.track.number %>
</p>

<%= link_to 'Edit', edit_stop_path(@stop) %> |
<%= link_to 'Back', stops_path %>