src/config/routes.rb
Rails.application.routes.draw do
  resources :homes
  root 'homes#index'
  resources :tracks
  resources :employees
  resources :crews
  resources :locomotives
  resources :wagons
  resources :ways
  resources :passengers
  resources :stops
  resources :stations
  get '/report_wagon' , to: 'wagons#report'
  get '/report_way' , to: 'ways#report'
  get '/report_1' , to: 'homes#track_delay'
  get '/report_2' , to: 'homes#report2'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

src/app/models/crew.rb
class Crew < ApplicationRecord
  has_many :employee_crews, dependent: :destroy
end

src/app/models/employee.rb
class Employee < ApplicationRecord
  has_many :work_histories, dependent: :destroy
  has_many :employee_crews, dependent: :destroy
end

src/app/models/employee_crew.rb
class EmployeeCrew < ApplicationRecord
  belongs_to :crew
  belongs_to :employee
end

src/app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :passenger
  belongs_to :way
end

src/app/models/home.rb
class Home < ApplicationRecord
end

src/app/models/locomotive.rb
class Locomotive < ApplicationRecord
  has_many :ways, dependent: :destroy
end

src/app/models/passenger.rb
class Passenger < ApplicationRecord

  has_many :feedbacks, dependent: :destroy
end

src/app/models/station.rb
class Station < ApplicationRecord
  has_many :stops, dependent: :destroy
end

src/app/models/stop.rb
class Stop < ApplicationRecord
  belongs_to :track
  belongs_to :station
end

src/app/models/track.rb
class Track < ApplicationRecord
  has_many :ways, dependent: :destroy
  has_many :stops, dependent: :destroy
end

src/app/models/wagon.rb
class Wagon < ApplicationRecord
  has_many :wagon_usage, dependent: :destroy
end

src/app/models/wagon_usage.rb
class WagonUsage < ApplicationRecord
  belongs_to :wagon
  belongs_to :way
end

src/app/models/way.rb
class Way < ApplicationRecord
  belongs_to :track
  belongs_to :locomotive
  has_many :feedbacks, dependent: :destroy
  has_many :work_histories, dependent: :destroy
  has_many :wagon_usage, dependent: :destroy
end

src/app/models/work_history.rb
class WorkHistory < ApplicationRecord
  belongs_to :way
  belongs_to :employee
end

src/app/controllers/wagons_controller.rb
class WagonsController < ApplicationController
  before_action :set_wagon, only: [:show, :edit, :update, :destroy]

  # GET /wagons
  # GET /wagons.json
  def index

    if params[:prod_year] != NIL
      @cislo = params[:prod_year].to_i
      @wagons = Wagon.where(production_year: @cislo..Float::INFINITY).paginate(:page => params[:page], :per_page => 50)
      #@wagons = Wagon.where(:production_year => @cislo)
    else
      @wagons = Wagon.all.paginate(:page => params[:page], :per_page => 50)
    end
  end

  # GET /wagons/1
  # GET /wagons/1.json
  def show
  end

  # GET /wagons/new
  def new
    @wagon = Wagon.new
  end

  # GET /wagons/1/edit
  def edit
  end

  # POST /wagons
  # POST /wagons.json
  def create
    Wagon.transaction do
    @wagon = Wagon.new(wagon_params)

    respond_to do |format|
      if @wagon.save
        format.html { redirect_to @wagon, notice: 'Wagon was successfully created.' }
        format.json { render :show, status: :created, location: @wagon }
      else
        format.html { render :new }
        format.json { render json: @wagon.errors, status: :unprocessable_entity }
      end
    end
      end
  end

  # PATCH/PUT /wagons/1
  # PATCH/PUT /wagons/1.json
  def update
    Wagon.transaction do
    respond_to do |format|
      if @wagon.update(wagon_params)
        format.html { redirect_to @wagon, notice: 'Wagon was successfully updated.' }
        format.json { render :show, status: :ok, location: @wagon }
      else
        format.html { render :edit }
        format.json { render json: @wagon.errors, status: :unprocessable_entity }
      end
      end
    end
  end

  # DELETE /wagons/1
  # DELETE /wagons/1.json
  def destroy
    Wagon.transaction do
    @wagon.destroy
    respond_to do |format|
      format.html { redirect_to wagons_url, notice: 'Wagon was successfully destroyed.' }
      format.json { head :no_content }
    end
      end
  end

  # GET /wagons
  # GET /wagons.json
  def report

  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_wagon
    @wagon = Wagon.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def wagon_params
    params.require(:wagon).permit(:production_year, :wagon_type)
  end
end

src/app/helpers/crews_helper.rb
module CrewsHelper
end

src/app/helpers/employees_helper.rb
module EmployeesHelper
end

src/app/helpers/homes_helper.rb
module HomesHelper
end

src/app/helpers/stations_helper.rb
module StationsHelper
end

src/app/helpers/stops_helper.rb
module StopsHelper
end

src/app/helpers/tracks_helper.rb
module TracksHelper
end

src/app/helpers/wagons_helper.rb
module WagonsHelper
end

src/app/helpers/ways_helper.rb
module WaysHelper
end

src/app/views/wagons/_form.html.erb
<%= form_with(model: wagon, local: true) do |form| %>
  <% if wagon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wagon.errors.count, "error") %> prohibited this wagon from being saved:</h2>

      <ul>
      <% wagon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :production_year %>
    <%= form.number_field :production_year, id: :wagon_production_year %>
  </div>

  <div class="field">
    <%= form.label :wagon_type %>
    <%= form.text_field :wagon_type, id: :wagon_wagon_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

src/app/views/wagons/edit.html.erb
<h1>Editing Wagon</h1>

<%= render 'form', wagon: @wagon %>

<%= link_to 'Show', @wagon %> |
<%= link_to 'Back', wagons_path %>

src/app/views/wagons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wagons</h1>

<table>
  <thead>
    <tr>
      <th>Production year</th>
      <th>Wagon type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wagons.each do |wagon| %>
      <tr>
        <td><%= wagon.production_year %></td>
        <td><%= wagon.wagon_type %></td>
        <td><%= link_to 'Show', wagon %></td>
        <td><%= link_to 'Edit', edit_wagon_path(wagon) %></td>
        <td><%= link_to 'Destroy', wagon, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Report', report_wagon_path %>
<%= link_to 'New Wagon', new_wagon_path %>
<%= link_to 'Back to all wagons', wagons_path %>


<%= will_paginate @wagons %>

src/app/views/wagons/new.html.erb
<h1>New Wagon</h1>

<%= render 'form', wagon: @wagon %>

<%= link_to 'Back', wagons_path %>

src/app/views/wagons/report.html.erb
<%= form_tag("/wagons", method: "get") do %>
  <%= label_tag(:prod_year, "Zadaj rok vyroby") %>
  <%= text_field_tag(:prod_year) %>
  <%= submit_tag("Hladaj") %>
<% end %>

<%= link_to 'Back', wagons_path %>

src/app/views/wagons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Production year:</strong>
  <%= @wagon.production_year %>
</p>

<p>
  <strong>Wagon type:</strong>
  <%= @wagon.wagon_type %>
</p>

<%= link_to 'Edit', edit_wagon_path(@wagon) %> |
<%= link_to 'Back', wagons_path %>