src/config/routes.rb
Rails.application.routes.draw do
  resources :homes
  root 'homes#index'
  resources :tracks
  resources :employees
  resources :crews
  resources :locomotives
  resources :wagons
  resources :ways
  resources :passengers
  resources :stops
  resources :stations
  get '/report_wagon' , to: 'wagons#report'
  get '/report_way' , to: 'ways#report'
  get '/report_1' , to: 'homes#track_delay'
  get '/report_2' , to: 'homes#report2'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

src/app/models/crew.rb
class Crew < ApplicationRecord
  has_many :employee_crews, dependent: :destroy
end

src/app/models/employee.rb
class Employee < ApplicationRecord
  has_many :work_histories, dependent: :destroy
  has_many :employee_crews, dependent: :destroy
end

src/app/models/employee_crew.rb
class EmployeeCrew < ApplicationRecord
  belongs_to :crew
  belongs_to :employee
end

src/app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :passenger
  belongs_to :way
end

src/app/models/home.rb
class Home < ApplicationRecord
end

src/app/models/locomotive.rb
class Locomotive < ApplicationRecord
  has_many :ways, dependent: :destroy
end

src/app/models/passenger.rb
class Passenger < ApplicationRecord

  has_many :feedbacks, dependent: :destroy
end

src/app/models/station.rb
class Station < ApplicationRecord
  has_many :stops, dependent: :destroy
end

src/app/models/stop.rb
class Stop < ApplicationRecord
  belongs_to :track
  belongs_to :station
end

src/app/models/track.rb
class Track < ApplicationRecord
  has_many :ways, dependent: :destroy
  has_many :stops, dependent: :destroy
end

src/app/models/wagon.rb
class Wagon < ApplicationRecord
  has_many :wagon_usage, dependent: :destroy
end

src/app/models/wagon_usage.rb
class WagonUsage < ApplicationRecord
  belongs_to :wagon
  belongs_to :way
end

src/app/models/way.rb
class Way < ApplicationRecord
  belongs_to :track
  belongs_to :locomotive
  has_many :feedbacks, dependent: :destroy
  has_many :work_histories, dependent: :destroy
  has_many :wagon_usage, dependent: :destroy
end

src/app/models/work_history.rb
class WorkHistory < ApplicationRecord
  belongs_to :way
  belongs_to :employee
end

src/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: [:show, :edit, :update, :destroy]

  # GET /tracks
  # GET /tracks.json
  def index
    @tracks = Track.all.paginate(:page => params[:page], :per_page => 50)
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
  end

  # GET /tracks/new
  def new
    @track = Track.new
  end

  # GET /tracks/1/edit
  def edit
  end

  # POST /tracks
  # POST /tracks.json
  def create
    Track.transaction do
    @track = Track.new(track_params)

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render :show, status: :created, location: @track }
      else
        format.html { render :new }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
    end
  end

  # PATCH/PUT /tracks/1
  # PATCH/PUT /tracks/1.json
  def update
    Track.transaction do
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { render :show, status: :ok, location: @track }
      else
        format.html { render :edit }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    Track.transaction do
    @track.destroy
    respond_to do |format|
      format.html { redirect_to tracks_url, notice: 'Track was successfully destroyed.' }
      format.json { head :no_content }
    end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def track_params
      params.require(:track).permit(:duration, :track_type, :number)
    end
end

src/app/helpers/crews_helper.rb
module CrewsHelper
end

src/app/helpers/employees_helper.rb
module EmployeesHelper
end

src/app/helpers/homes_helper.rb
module HomesHelper
end

src/app/helpers/stations_helper.rb
module StationsHelper
end

src/app/helpers/stops_helper.rb
module StopsHelper
end

src/app/helpers/tracks_helper.rb
module TracksHelper
end

src/app/helpers/wagons_helper.rb
module WagonsHelper
end

src/app/helpers/ways_helper.rb
module WaysHelper
end

src/app/views/tracks/_form.html.erb
<%= form_with(model: track, local: true) do |form| %>
  <% if track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
      <% track.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration, id: :track_duration %>
  </div>

  <div class="field">
    <%= form.label :track_type %>
    <%= form.text_field :track_type, id: :track_track_type %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number, id: :track_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

src/app/views/tracks/edit.html.erb
<h1>Editing Track</h1>

<%= render 'form', track: @track %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %>

src/app/views/tracks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tracks</h1>

<table>
  <thead>
    <tr>
      <th>Duration</th>
      <th>Track type</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tracks.each do |track| %>
      <tr>
        <td><%= track.duration %></td>
        <td><%= track.track_type %></td>
        <td><%= track.number %></td>
        <td><%= link_to 'Show', track %></td>
        <td><%= link_to 'Edit', edit_track_path(track) %></td>
        <td><%= link_to 'Destroy', track, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= will_paginate @tracks %>
<%= link_to 'New Track', new_track_path %>

src/app/views/tracks/new.html.erb
<h1>New Track</h1>

<%= render 'form', track: @track %>

<%= link_to 'Back', tracks_path %>

src/app/views/tracks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Duration:</strong>
  <%= @track.duration %>
</p>

<p>
  <strong>Track type:</strong>
  <%= @track.track_type %>
</p>

<p>
  <strong>Number:</strong>
  <%= @track.number %>
</p>

<%= link_to 'Edit', edit_track_path(@track) %> |
<%= link_to 'Back', tracks_path %>