src/config/routes.rb
Rails.application.routes.draw do
  resources :homes
  root 'homes#index'
  resources :tracks
  resources :employees
  resources :crews
  resources :locomotives
  resources :wagons
  resources :ways
  resources :passengers
  resources :stops
  resources :stations
  get '/report_wagon' , to: 'wagons#report'
  get '/report_way' , to: 'ways#report'
  get '/report_1' , to: 'homes#track_delay'
  get '/report_2' , to: 'homes#report2'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

src/app/models/crew.rb
class Crew < ApplicationRecord
  has_many :employee_crews, dependent: :destroy
end

src/app/models/employee.rb
class Employee < ApplicationRecord
  has_many :work_histories, dependent: :destroy
  has_many :employee_crews, dependent: :destroy
end

src/app/models/employee_crew.rb
class EmployeeCrew < ApplicationRecord
  belongs_to :crew
  belongs_to :employee
end

src/app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :passenger
  belongs_to :way
end

src/app/models/home.rb
class Home < ApplicationRecord
end

src/app/models/locomotive.rb
class Locomotive < ApplicationRecord
  has_many :ways, dependent: :destroy
end

src/app/models/passenger.rb
class Passenger < ApplicationRecord

  has_many :feedbacks, dependent: :destroy
end

src/app/models/station.rb
class Station < ApplicationRecord
  has_many :stops, dependent: :destroy
end

src/app/models/stop.rb
class Stop < ApplicationRecord
  belongs_to :track
  belongs_to :station
end

src/app/models/track.rb
class Track < ApplicationRecord
  has_many :ways, dependent: :destroy
  has_many :stops, dependent: :destroy
end

src/app/models/wagon.rb
class Wagon < ApplicationRecord
  has_many :wagon_usage, dependent: :destroy
end

src/app/models/wagon_usage.rb
class WagonUsage < ApplicationRecord
  belongs_to :wagon
  belongs_to :way
end

src/app/models/way.rb
class Way < ApplicationRecord
  belongs_to :track
  belongs_to :locomotive
  has_many :feedbacks, dependent: :destroy
  has_many :work_histories, dependent: :destroy
  has_many :wagon_usage, dependent: :destroy
end

src/app/models/work_history.rb
class WorkHistory < ApplicationRecord
  belongs_to :way
  belongs_to :employee
end

src/app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
  before_action :set_passenger, only: [:show, :edit, :update, :destroy]

  # GET /passengers
  # GET /passengers.json
  def index
    @passengers = Passenger.all.paginate(:page => params[:page], :per_page => 50)
  end

  # GET /passengers/1
  # GET /passengers/1.json
  def show
  end

  # GET /passengers/new
  def new
    @passenger = Passenger.new
  end

  # GET /passengers/1/edit
  def edit
  end

  # POST /passengers
  # POST /passengers.json
  def create
    Passenger.transaction do
    @passenger = Passenger.new(passenger_params)

    respond_to do |format|
      if @passenger.save
        format.html { redirect_to @passenger, notice: 'Passenger was successfully created.' }
        format.json { render :show, status: :created, location: @passenger }
      else
        format.html { render :new }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
      end
  end

  # PATCH/PUT /passengers/1
  # PATCH/PUT /passengers/1.json
  def update
    Passenger.transaction do
    respond_to do |format|
      if @passenger.update(passenger_params)
        format.html { redirect_to @passenger, notice: 'Passenger was successfully updated.' }
        format.json { render :show, status: :ok, location: @passenger }
      else
        format.html { render :edit }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
      end
    end
  end

  # DELETE /passengers/1
  # DELETE /passengers/1.json
  def destroy
    Passenger.transaction do
    @passenger.destroy
    respond_to do |format|
      format.html { redirect_to passengers_url, notice: 'Passenger was successfully destroyed.' }
      format.json { head :no_content }
    end
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_passenger
      @passenger = Passenger.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def passenger_params
      params.require(:passenger).permit(:first_name, :last_name, :birth_date, :entry_station, :exit_station)
    end
end

src/app/helpers/crews_helper.rb
module CrewsHelper
end

src/app/helpers/homes_helper.rb
module HomesHelper
end

src/app/helpers/passengers_helper.rb
module PassengersHelper
end

src/app/helpers/stations_helper.rb
module StationsHelper
end

src/app/helpers/stops_helper.rb
module StopsHelper
end

src/app/helpers/tracks_helper.rb
module TracksHelper
end

src/app/helpers/wagons_helper.rb
module WagonsHelper
end

src/app/helpers/ways_helper.rb
module WaysHelper
end

src/app/views/passengers/_form.html.erb
<%= form_with(model: passenger, local: true) do |form| %>
  <% if passenger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(passenger.errors.count, "error") %> prohibited this passenger from being saved:</h2>

      <ul>
      <% passenger.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :passenger_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :passenger_last_name %>
  </div>

  <div class="field">
    <%= form.label :birth_date %>
    <%= form.date_select :birth_date, id: :passenger_birth_date %>
  </div>

  <div class="field">
    <%= form.label :entry_station %>
    <%= form.number_field :entry_station, id: :passenger_entry_station %>
  </div>

  <div class="field">
    <%= form.label :exit_station %>
    <%= form.number_field :exit_station, id: :passenger_exit_station %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

src/app/views/passengers/edit.html.erb
<h1>Editing Passenger</h1>

<%= render 'form', passenger: @passenger %>

<%= link_to 'Show', @passenger %> |
<%= link_to 'Back', passengers_path %>

src/app/views/passengers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Passengers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Birth date</th>
      <th>Entry station</th>
      <th>Exit station</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @passengers.each do |passenger| %>
      <tr>
        <td><%= passenger.first_name %></td>
        <td><%= passenger.last_name %></td>
        <td><%= passenger.birth_date %></td>
        <td><%= passenger.entry_station %></td>
        <td><%= passenger.exit_station %></td>
        <td><%= link_to 'Show', passenger %></td>
        <td><%= link_to 'Edit', edit_passenger_path(passenger) %></td>
        <td><%= link_to 'Destroy', passenger, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= will_paginate @passengers %>
<%= link_to 'New Passenger', new_passenger_path %>

src/app/views/passengers/new.html.erb
<h1>New Passenger</h1>

<%= render 'form', passenger: @passenger %>

<%= link_to 'Back', passengers_path %>

src/app/views/passengers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @passenger.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @passenger.last_name %>
</p>

<p>
  <strong>Birth date:</strong>
  <%= @passenger.birth_date %>
</p>

<p>
  <strong>Entry station:</strong>
  <%= @passenger.entry_station %>
</p>

<p>
  <strong>Exit station:</strong>
  <%= @passenger.exit_station %>
</p>

<%= link_to 'Edit', edit_passenger_path(@passenger) %> |
<%= link_to 'Back', passengers_path %>